spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diary
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  h2:
#    console:
#      enabled: true # 브라우저에서 localhost:8080/h2-console 접속 가능하게 설정
#      path: /h2-console

  jpa:
    hibernate:
      # 엔티티 클래스를 보고 테이블을 자동 생성/수정
      ddl-auto: update
    show-sql: true # 터미널에 JPA가 날리는 SQL문 출력
    properties:
      hibernate:
        format_sql: true
file:
  dir: ${FILE_DIR}
ai:
  server:
    url: ${AI_SERVER_URL:http://localhost:8000}